### ISSUE TITLE
Passing different values many times on a page appends previous content

### ISSUE THREAD

**Issue by iantearle** [spyrosoft/php-format-html-output#1]
Hi, I am calling HTML() a few times on my page, but on the subsequent times it is appending the first instance to the result. I may be missing something really simple, but cant see it staring at my screen this morning. 

$format->HTML($items->descr) - is fine.

$format->HTML($items->dates) - has the dates plus the descr appended before its output.

**Comment by spyrosoft** [comment]
Good catch, Ian! Thanks. It needed a line to set $this->output back to
an empty string at the beginning of the $format->html() function.

-- Bennett
